const railStations = [
{ id: "0", route: "0", text: "Airport", name: "AIRPORT"}, 
{ id: "1", route: "1", text: "Arts Center", name: "ARTS CENTER"}, 
{ id: "2", route: "2", text: "Ashby", name: "ASHBY"}, 
{ id: "3", route: "3", text: "Avondale", name: "AVONDALE"}, 
{ id: "4", route: "4", text: "Bankhead", name: "BANKHEAD"}, 
{ id: "5", route: "5", text: "Brookhaven / Oglethorpe", name: "BROOKHAVEN"}, 
{ id: "6", route: "6", text: "Buckhead", name: "BUCKHEAD"}, 
{ id: "7", route: "7", text: "Chamblee", name: "CHAMBLEE"}, 
{ id: "8", route: "8", text: "Civic Center", name: "CIVIC CENTER"}, 
{ id: "9", route: "9", text: "College Park", name: "COLLEGE PARK"}, 
{ id: "10", route: "10", text: "Decatur", name: "DECATUR"}, 
{ id: "11", route: "11", text: "GWCC/CNN Center", name: "OMNI DOME"}, 
{ id: "12", route: "12", text: "Doraville", name: "DORAVILLE"}, 
{ id: "13", route: "13", text: "Dunwoody", name: "DUNWOODY"}, 
{ id: "14", route: "14", text: "East Lake", name: "EAST LAKE"}, 
{ id: "15", route: "15", text: "East Point", name: "EAST POINT"}, 
{ id: "16", route: "16", text: "Edgewood / Candler Park", name: "EDGEWOOD / CANDLER PARK"}, 
{ id: "17", route: "17", text: "Five Points", name: "FIVE POINTS"}, 
{ id: "18", route: "18", text: "Garnett", name: "GARNETT"}, 
{ id: "19", route: "19", text: "Georgia State", name: "GEORGIA STATE"}, 
{ id: "20", route: "20", text: "Hamilton E. Holmes", name: "HAMILTON E. HOLMES"}, 
{ id: "21", route: "21", text: "Indian Creek", name: "INDIAN CREEK"}, 
{ id: "22", route: "22", text: "Inman Park / Reynoldstown", name: "INMAN PARK"}, 
{ id: "23", route: "23", text: "Kensington", name: "KENSINGTON"}, 
{ id: "24", route: "24", text: "King Memorial", name: "KING MEMORIAL"}, 
{ id: "25", route: "25", text: "Lakewood / Ft. McPherson", name: "LAKEWOOD"}, 
{ id: "26", route: "26", text: "Lenox", name: "LENOX"}, 
{ id: "27", route: "27", text: "Lindbergh Center", name: "LINDBERGH"}, 
{ id: "28", route: "28", text: "Medical Center", name: "MEDICAL CENTER"}, 
{ id: "29", route: "29", text: "Midtown", name: "MIDTOWN"}, 
{ id: "30", route: "30", text: "North Ave", name: "NORTH AVE"}, 
{ id: "31", route: "31", text: "North Springs", name: "NORTH SPRINGS"}, 
{ id: "32", route: "32", text: "Oakland City", name: "OAKLAND CITY"}, 
{ id: "33", route: "33", text: "Peachtree Center", name: "PEACHTREE CENTER"}, 
{ id: "34", route: "34", text: "Sandy Springs", name: "SANDY SPRINGS"}, 
{ id: "35", route: "35", text: "Vine City", name: "VINE CITY"}, 
{ id: "36", route: "36", text: "West End", name: "WEST END"}, 
{ id: "37", route: "37", text: "West Lake", name: "WEST LAKE"}, 
]

module.exports = railStations