
module.exports = [
		"Airport",
		"Arts Center",
		"Ashby",
		"Avondale",
		"Bankhead",
		"Brookhaven / Oglethorpe",
		"Buckhead",
		"Chamblee",
		"Civic Center",
		"College Park",
		"Decatur",
		"GWCC/CNN Center",
		"Doraville",
		"Dunwoody",
		"East Lake",
		"East Point",
		"Edgewood / Candler Park",
		"Five Points",
		"Garnett",
		"Georgia State",
		"Hamilton E. Holmes",
		"Indian Creek",
		"Inman Park / Reynoldstown",
		"Kensington",
		"King Memorial",
		"Lakewood / Ft. McPherson",
		"Lenox",
		"Lindbergh Center",
		"Medical Center",
		"Midtown",
		"North Ave",
		"North Springs",
		"Oakland City",
		"Peachtree Center",
		"Sandy Springs",
		"Vine City",
		"West End",
		"West Lake"
];